class EmojiUtil {


  static List<Map<String, String>> pages = [emojiPage1,emojiPage2,emojiPage3,emojiPage4];

  static Map<String, String> emojiPage1 = {
    "[微笑]": "images/emoji/fuck01.png",
    "[撇嘴]": "images/emoji/fuck02.png",
    "[色]": "images/emoji/fuck03.png",
    "[发呆]": "images/emoji/fuck04.png",
    "[得意]": "images/emoji/fuck05.png",
    "[流泪]": "images/emoji/fuck06.png",
    "[害羞]": "images/emoji/fuck07.png",
    "[闭嘴]": "images/emoji/fuck08.png",
    "[睡]": "images/emoji/fuck09.png",
    "[大哭]": "images/emoji/fuck10.png",
    "[尴尬]": "images/emoji/fuck11.png",
    "[发怒]": "images/emoji/fuck12.png",
    "[调皮]": "images/emoji/fuck13.png",
    "[呲牙]": "images/emoji/fuck14.png",
    "[惊讶]": "images/emoji/fuck15.png",
    "[难过]": "images/emoji/fuck16.png",
    "[囧]": "images/emoji/fuck18.png",
    "[抓狂]": "images/emoji/fuck19.png",
    "[吐]": "images/emoji/fuck20.png",
    "[偷笑]": "images/emoji/fuck21.png",

  };

  static Map<String, String> emojiPage2 = {
    "[愉快]": "images/emoji/fuck22.png",
    "[白眼]": "images/emoji/fuck23.png",
    "[傲慢]": "images/emoji/fuck24.png",
    "[困]": "images/emoji/fuck26.png",
    "[惊恐]": "images/emoji/fuck27.png",
    "[流汗]": "images/emoji/fuck28.png",
    "[憨笑]": "images/emoji/fuck29.png",
    "[悠闲]": "images/emoji/fuck30.png",
    "[奋斗]": "images/emoji/fuck31.png",
    "[咒骂]": "images/emoji/fuck32.png",
    "[疑问]": "images/emoji/fuck33.png",
    "[嘘]": "images/emoji/fuck34.png",
    "[晕]": "images/emoji/fuck35.png",
    "[衰]": "images/emoji/fuck37.png",
    "[骷髅]": "images/emoji/fuck38.png",
    "[敲打]": "images/emoji/fuck39.png",
    "[再见]": "images/emoji/fuck40.png",
    "[擦汗]": "images/emoji/fuck41.png",
    "[抠鼻]": "images/emoji/fuck42.png",
    "[鼓掌]": "images/emoji/fuck43.png",
  };
  static Map<String, String> emojiPage3 = {
    "[坏笑]": "images/emoji/fuck45.png",
    "[左哼哼]": "images/emoji/fuck46.png",
    "[右哼哼]": "images/emoji/fuck47.png",
    "[哈欠]": "images/emoji/fuck48.png",
    "[鄙视]": "images/emoji/fuck49.png",
    "[委屈]": "images/emoji/fuck50.png",
    "[快哭了]": "images/emoji/fuck51.png",
    "[阴险]": "images/emoji/fuck52.png",
    "[亲亲]": "images/emoji/fuck53.png",
    "[可怜]": "images/emoji/fuck55.png",
    "[菜刀]": "images/emoji/fuck56.png",
    "[西瓜]": "images/emoji/fuck57.png",
    "[啤酒]": "images/emoji/fuck58.png",
    "[咖啡]": "images/emoji/fuck61.png",
    "[猪头]": "images/emoji/fuck63.png",
    "[玫瑰]": "images/emoji/fuck64.png",
    "[凋谢]": "images/emoji/fuck65.png",
    "[嘴唇]": "images/emoji/fuck66.png",
    "[爱心]": "images/emoji/fuck67.png",
    "[心碎]": "images/emoji/fuck68.png",
  };
  static Map<String, String> emojiPage4 = {
    "[蛋糕]": "images/emoji/fuck69.png",
    "[炸弹]": "images/emoji/fuck71.png",
    "[便便]": "images/emoji/fuck75.png",
    "[月亮]": "images/emoji/fuck76.png",
    "[太阳]": "images/emoji/fuck77.png",
    "[拥抱]": "images/emoji/fuck79.png",
    "[强]": "images/emoji/fuck80.png",
    "[弱]": "images/emoji/fuck81.png",
    "[握手]": "images/emoji/fuck82.png",
    "[胜利]": "images/emoji/fuck83.png",
    "[抱拳]": "images/emoji/fuck84.png",
    "[勾引]": "images/emoji/fuck85.png",
    "[拳头]": "images/emoji/fuck86.png",
    "[OK]": "images/emoji/fuck90.png",
    "[跳跳]": "images/emoji/fuck93.png",
    "[发抖]": "images/emoji/fuck94.png",
    "[怄火]": "images/emoji/fuck95.png",
    "[转圈]": "images/emoji/fuck96.png",
    "[嘿哈]": "images/emoji/fuck97.png",
    "[捂脸]": "images/emoji/fuck98.png",
//    "[奸笑]": "images/emoji/fuck99.png",
//    "[机智]": "images/emoji/fuck100.png",
  };
  static Map<String, String> emojiMap = {
    "[微笑]": "images/emoji/fuck01.png",
    "[撇嘴]": "images/emoji/fuck02.png",
    "[色]": "images/emoji/fuck03.png",
    "[发呆]": "images/emoji/fuck04.png",
    "[得意]": "images/emoji/fuck05.png",
    "[流泪]": "images/emoji/fuck06.png",
    "[害羞]": "images/emoji/fuck07.png",
    "[闭嘴]": "images/emoji/fuck08.png",
    "[睡]": "images/emoji/fuck09.png",
    "[大哭]": "images/emoji/fuck10.png",
    "[尴尬]": "images/emoji/fuck11.png",
    "[发怒]": "images/emoji/fuck12.png",
    "[调皮]": "images/emoji/fuck13.png",
    "[呲牙]": "images/emoji/fuck14.png",
    "[惊讶]": "images/emoji/fuck15.png",
    "[难过]": "images/emoji/fuck16.png",
    "[囧]": "images/emoji/fuck18.png",
    "[抓狂]": "images/emoji/fuck19.png",
    "[吐]": "images/emoji/fuck20.png",
    "[偷笑]": "images/emoji/fuck21.png",

    "[愉快]": "images/emoji/fuck22.png",
    "[白眼]": "images/emoji/fuck23.png",
    "[傲慢]": "images/emoji/fuck24.png",
    "[困]": "images/emoji/fuck26.png",
    "[惊恐]": "images/emoji/fuck27.png",
    "[流汗]": "images/emoji/fuck28.png",
    "[憨笑]": "images/emoji/fuck29.png",
    "[悠闲]": "images/emoji/fuck30.png",
    "[奋斗]": "images/emoji/fuck31.png",
    "[咒骂]": "images/emoji/fuck32.png",
    "[疑问]": "images/emoji/fuck33.png",
    "[嘘]": "images/emoji/fuck34.png",
    "[晕]": "images/emoji/fuck35.png",
    "[衰]": "images/emoji/fuck37.png",
    "[骷髅]": "images/emoji/fuck38.png",
    "[敲打]": "images/emoji/fuck39.png",
    "[再见]": "images/emoji/fuck40.png",
    "[擦汗]": "images/emoji/fuck41.png",
    "[抠鼻]": "images/emoji/fuck42.png",
    "[鼓掌]": "images/emoji/fuck43.png",

    "[坏笑]": "images/emoji/fuck45.png",
    "[左哼哼]": "images/emoji/fuck46.png",
    "[右哼哼]": "images/emoji/fuck47.png",
    "[哈欠]": "images/emoji/fuck48.png",
    "[鄙视]": "images/emoji/fuck49.png",
    "[委屈]": "images/emoji/fuck50.png",
    "[快哭了]": "images/emoji/fuck51.png",
    "[阴险]": "images/emoji/fuck52.png",
    "[亲亲]": "images/emoji/fuck53.png",
    "[可怜]": "images/emoji/fuck55.png",
    "[菜刀]": "images/emoji/fuck56.png",
    "[西瓜]": "images/emoji/fuck57.png",
    "[啤酒]": "images/emoji/fuck58.png",
    "[咖啡]": "images/emoji/fuck61.png",
    "[猪头]": "images/emoji/fuck63.png",
    "[玫瑰]": "images/emoji/fuck64.png",
    "[凋谢]": "images/emoji/fuck65.png",
    "[嘴唇]": "images/emoji/fuck66.png",
    "[爱心]": "images/emoji/fuck67.png",
    "[心碎]": "images/emoji/fuck68.png",

    "[蛋糕]": "images/emoji/fuck69.png",
    "[炸弹]": "images/emoji/fuck71.png",
    "[便便]": "images/emoji/fuck75.png",
    "[月亮]": "images/emoji/fuck76.png",
    "[太阳]": "images/emoji/fuck77.png",
    "[拥抱]": "images/emoji/fuck79.png",
    "[强]": "images/emoji/fuck80.png",
    "[弱]": "images/emoji/fuck81.png",
    "[握手]": "images/emoji/fuck82.png",
    "[胜利]": "images/emoji/fuck83.png",
    "[抱拳]": "images/emoji/fuck84.png",
    "[勾引]": "images/emoji/fuck85.png",
    "[拳头]": "images/emoji/fuck86.png",
    "[OK]": "images/emoji/fuck90.png",
    "[跳跳]": "images/emoji/fuck93.png",
    "[发抖]": "images/emoji/fuck94.png",
    "[怄火]": "images/emoji/fuck95.png",
    "[转圈]": "images/emoji/fuck96.png",
    "[嘿哈]": "images/emoji/fuck97.png",
    "[捂脸]": "images/emoji/fuck98.png",
    "[奸笑]": "images/emoji/fuck99.png",
    "[机智]": "images/emoji/fuck100.png",
  };
}
